### ISSUE TITLE
Unit test utilities

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/sdk-java#13]
We should port unit test utilities from the old SDK

```[tasklist]
- [ ] https://github.com/restatedev/sdk-java/issues/57
- [ ] https://github.com/restatedev/sdk-java/issues/59
- [ ] https://github.com/restatedev/sdk-java/issues/58
```
