### ISSUE TITLE
Release Java SDK

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/sdk-java#146]
We want to release the Java SDK to our users. This issue tracks the open tasks that need to be completed.

```[tasklist]
### Tasks
- [ ] #116
- [ ] https://github.com/restatedev/sdk-java/issues/158
- [ ] https://github.com/restatedev/sdk-java/issues/147
- [ ] https://github.com/restatedev/sdk-java/issues/35#issuecomment-1825405967
- [ ] https://github.com/restatedev/sdk-java/issues/163
- [ ] https://github.com/restatedev/sdk-java/issues/22
- [ ] https://github.com/restatedev/documentation/issues/177
- [ ] https://github.com/restatedev/documentation/issues/175
- [ ] https://github.com/restatedev/documentation/issues/176
- [ ] https://github.com/restatedev/examples/issues/40
```

**Comment by slinkydeveloper** [comment]
Done
