### ISSUE TITLE
Publish Java artifacts to maven central

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/sdk-java#147]
We want to publish the Java SDK on [Maven central](https://central.sonatype.com/).

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/sdk-java/issues/150
- [ ] https://github.com/restatedev/sdk-java/issues/149
- [ ] https://github.com/restatedev/sdk-java/issues/148
```
