### ISSUE TITLE
Harden API surface of the SDK

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/sdk-java#25]
This includes both Blocking Java and Kotlin SDK 

```[tasklist]
* [x] #9
* [x] #2
* [x] #19
* [x] #38
* [x] https://github.com/restatedev/sdk-java/issues/45
* [ ] https://github.com/restatedev/sdk-java/issues/15
* [ ] https://github.com/restatedev/sdk-java/issues/50
```
